# Generated by Django 4.1.4 on 2022-12-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendschat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedemails',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='authorizedemails',
            name='email_suffix',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='friends',
            field=models.ManyToManyField(default=None, null=True, to='friendschat.chatuser'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='google_pic',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
