# Generated by Django 4.1.4 on 2022-12-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendschat', '0002_alter_authorizedemails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='friends',
            field=models.ManyToManyField(default=None, to='friendschat.chatuser'),
        ),
    ]
