# Generated by Django 4.1.4 on 2022-12-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendschat', '0003_alter_chatuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
