# Generated by Django 4.1.4 on 2022-12-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendschat', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_key',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
