# Generated by Django 4.1.4 on 2022-12-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendschat', '0006_chatmessage_message_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='description',
            field=models.CharField(blank=True, default='This person wrote nothing.', max_length=300),
        ),
    ]
