# Generated by Django 4.1.4 on 2022-12-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendschat', '0007_chatuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='send_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
