# Generated by Django 4.1.4 on 2022-12-28 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendschat', '0009_alter_chatuser_related_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField()),
                ('request_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='friendschat.chatuser')),
                ('request_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='friendschat.chatuser')),
            ],
        ),
    ]
